# Take-Home Exercise 1: From Data to Evidence
## Assignment Details
**Module Title:** Data Analytics  
**CRN:** 23631
**Student:** Rory Patrick Sheridan - A00082654  
**Submission File:** `A00082654_Rory_Sheridan_A1.pdf`  
**Dataset:**
FreshPack Foods batch-level production and quality data, `Take_Home_LabExercise_1_Dataset.csv`.  
**Task:**
Inspect a dataset, identify data-quality issues, choose suitable summaries and visualisations, quantify patterns, apply introductory statistical inference, and communicate what the evidence does and does not support.

Github Repository:  
https://github.com/Ri-Dearg/da-labs  
Github Notebook:  
https://github.com/Ri-Dearg/da-labs/blob/main/lab1_data_evidence.ipynb

## Summary
**Findings TBD**

## Table of Contents

<details>
<summary><a href="#tools--libraries">Tools & Libraries</a></summary>

- [Libraries](#libraries)

</details>
<details>
<summary><a href="#question-1-understand-and-audit-the-data">Question 1: Understand and Audit the Data</a></summary>

- [Go to section](#question-1-understand-and-audit-the-data)

</details>

## Tools & Libraries
1. [Pandas](https://pandas.pydata.org) - Dataframes and data manipulation
2. [Jupyter](https://jupyter.org) - Notebook Tool

### Libraries
Libraries used.

In [1]:
import pandas as pd

## Question 1: Understand and Audit the Data

### a) Identify the observational unit. For each variable, classify it as identifier/date/categorical/ordinal/quantitative and, where relevant, state the measurement scale.

**Observational unit:** One batch of food.

| Variable Name | Type | Measurement Scale | Unit |
|---|---|---|---|
| `Batch_ID` | Identifier | Nominal |  |
| `Production_Date` | Date | Interval | Day |
| `Factory` | Categorical | Nominal |  |
| `Process_Type` | Categorical | Nominal |  |
| `Shift` | Categorical | Nominal |  |
| `Product_Weight_g` | quantitative | Ratio | Grams |
| `Moisture_pct` | quantitative | Ratio | Percent |
| `Temperature_C` | quantitative | Interval | Celsius |
| `Processing_Time_min` | quantitative | Ratio | Minute |
| `Quality_Grade` | Ordinal | Ordinal |  |
| `Defect` | Categorical | Nominal |  |

In [2]:
df = pd.read_csv('products.csv')
df.head()

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Product_Weight_g,Moisture_pct,Temperature_C,Processing_Time_min,Quality_Grade,Defect
0,B001,2026-09-17,B,Enhanced,Day,482.9,11.18,21.0,33.5,B,Yes
1,B002,2026-09-07,C,Standard,Day,496.3,11.17,22.1,33.6,A,No
2,B003,2026-09-14,B,Standard,Night,492.3,11.65,20.5,35.8,A,No
3,B004,2026-09-16,C,Standard,Day,513.1,11.55,20.5,37.6,B,No
4,B005,2026-09-10,A,Enhanced,Day,494.5,12.57,21.6,45.7,B,Yes

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Batch_ID             120 non-null    str
 1   Production_Date      120 non-null    str
 2   Factory              120 non-null    str
 3   Process_Type         120 non-null    str
 4   Shift                120 non-null    str
 5   Product_Weight_g     120 non-null    float64
 6   Moisture_pct         118 non-null    float64
 7   Temperature_C        120 non-null    float64
 8   Processing_Time_min  119 non-null    float64
 9   Quality_Grade        119 non-null    str
 10  Defect               120 non-null    str
dtypes: float64(4), str(7)
memory usage: 10.4 KB

### b) Audit the dataset before analysis. Quantify missing values, duplicated records, suspicious or implausible values, and any other data-quality issue you consider material.

Audit:
- Four missing values: 2 in `Moisture_pct`, 1 in `Processing_Time_min`, and 1 in `Quality_Grade`.
- 1 duplicated record on row 118, `Batch_ID` B048 .
- 1 suspicious value on `Product_Weight_g` at 568g, another on `Processing_Time_min` at 112, 1 implausible value on `Temperature_C` at 210.0.
- `Quality_Grade` and `Defect` don't align although it appears they should.
- `Production_Date` is type `str` rather than `DateTime`

In [4]:
df.describe()

       Product_Weight_g  Moisture_pct  Temperature_C  Processing_Time_min
count        120.000000    118.000000     120.000000           119.000000
mean         501.530833     11.660339      23.077500            41.831933
std           11.582621      0.701214      17.243888             8.606560
min          476.200000      9.610000      18.200000            26.400000
25%          494.775000     11.190000      20.800000            37.750000
50%          501.800000     11.660000      21.500000            41.700000
75%          508.700000     12.097500      22.200000            44.950000
max          568.000000     13.510000     210.000000           112.000000

In [5]:
df.describe(exclude='number')

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Quality_Grade,Defect
count,120,120,120,120,120,119,120
unique,119,27,3,2,2,3,2
top,B048,2026-09-17,A,Standard,Day,B,No
freq,2,9,45,65,79,77,107

In [6]:
df.shape

(120, 11)

In [7]:
df.duplicated().sum()

np.int64(1)

In [8]:
df[df.duplicated()]

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Product_Weight_g,Moisture_pct,Temperature_C,Processing_Time_min,Quality_Grade,Defect
118,B048,2026-09-18,A,Standard,Day,488.5,12.18,23.0,37.7,B,No

In [9]:
df.isna().sum()

Batch_ID               0
Production_Date        0
Factory                0
Process_Type           0
Shift                  0
Product_Weight_g       0
Moisture_pct           2
Temperature_C          0
Processing_Time_min    1
Quality_Grade          1
Defect                 0
dtype: int64

### c) Produce a short data-treatment log stating what you would keep, correct, exclude, or leave unchanged and why. State the analysis sample size(s) resulting from your decisions.

The set began with 120 rows. After data treatment 1 duplicate was removed and 119 rows remained.

- The duplicate shared the value `B048` with another row. All other values are also identical. Since the batch identifier should be a unique value, and all other rows have unique identifiers, I have chosen to drop it.
- There were four rows with missing values, which is a minimal amount of missing data for the dataset, so I chose to simply keep the rows. If issues arise later, I will reexamine the choice.
- The implausible temperature value of 210 seemed like erroneous data entry, as a decimal point would place it within a normal range. I have chosen to correct it directly as 21.0 For this reason.
- The other two values did not indicate erroneous data entry, so I have chosen to keep them in the case they are genuine.
- I changed the `Production_Date` to a `datetime` type so dates are stored and interpreted correctly.

In [10]:
df_dedup = df.drop_duplicates()
df_dedup.duplicated().sum()

np.int64(0)

In [11]:
df_temp = df_dedup.replace({'Temperature_C': {210: 21.0}})
df_temp.describe()

       Product_Weight_g  Moisture_pct  Temperature_C  Processing_Time_min
count        119.000000    117.000000     119.000000           118.000000
mean         501.640336     11.655897      21.489916            41.866949
std           11.569051      0.702561       1.124488             8.634745
min          476.200000      9.610000      18.200000            26.400000
25%          494.900000     11.190000      20.800000            37.800000
50%          502.000000     11.650000      21.500000            41.800000
75%          508.900000     12.090000      22.200000            44.975000
max          568.000000     13.510000      24.100000           112.000000

In [12]:
df_temp['Production_Date'] = df_temp['Production_Date'].astype('datetime64[ns]')
df_clean = df_temp.copy()

In [13]:
df_clean.head()

,Batch_ID,Production_Date,Factory,Process_Type,Shift,Product_Weight_g,Moisture_pct,Temperature_C,Processing_Time_min,Quality_Grade,Defect
0,B001,2026-09-17,B,Enhanced,Day,482.9,11.18,21.0,33.5,B,Yes
1,B002,2026-09-07,C,Standard,Day,496.3,11.17,22.1,33.6,A,No
2,B003,2026-09-14,B,Standard,Night,492.3,11.65,20.5,35.8,A,No
3,B004,2026-09-16,C,Standard,Day,513.1,11.55,20.5,37.6,B,No
4,B005,2026-09-10,A,Enhanced,Day,494.5,12.57,21.6,45.7,B,Yes

In [14]:
print(df.shape[0] - df_clean.shape[0])
df_clean.shape[0]

1

119

b) Produce no more than five well-designed figures that collectively examine: (i) at least one distribution, (ii) at least
one comparison across groups, (iii) at least one categorical pattern, and (iv) at least one relationship between two
quantitative variables.